apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/mysql-pv"