apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-0
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mysql-pv-0   
