apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client-role-binding
  namespace: client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: client-role
subjects:
- kind: ServiceAccount
  name: client-account
  namespace: client