apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 10.0.203.75:5555/mysql-image:latest
      ports:
        - containerPort: 3306
      envFrom: 
        - secretRef:
            name: mysql-config
        - configMapRef: 
            name: mysql-config 
      volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: init-sql
      configMap:
        name: mysql-init