apiVersion: v1
kind: Service
metadata:
  name: admin-external-service
  namespace: admin
spec:
  type: NodePort
  selector:
    app: admin-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080